fn main() {
    println!("Task-shell guides index");
    println!();
    println!("CLI storefront:");
    println!("  - cargo run -- --showcase");
    println!("    Minimal top-level crate showcase from `src/main.rs`.");
    println!();
    println!("Task dispatch / shell infrastructure:");
    println!("  - examples/task_dispatcher_guide.rs");
    println!("    Unified IVP/BVP document dispatcher (`solver: IVP|BVP`).");
    println!("  - examples/legacy_main_compat.rs");
    println!("    Legacy numbered-example compatibility bridge.");
    println!();
    println!("IVP task shell:");
    println!("  - examples/ivp_task_shell_guide.rs");
    println!("    Minimal explicit/nonstiff text-driven IVP example.");
    println!("  - examples/ivp_task_shell_backward_euler_guide.rs");
    println!("    Text-driven stiff IVP with Backward Euler.");
    println!("  - examples/ivp_task_shell_bdf_guide.rs");
    println!("    Text-driven stiff IVP with BDF.");
    println!("  - examples/lsode2_task_shell_guide.rs");
    println!("    Text-driven LSODE2 guide (method aliases, lsode2_* options).");
    println!("  - examples/ivp_task_shell_radau_guide.rs");
    println!("    Text-driven stiff IVP with Radau5.");
    println!();
    println!("BVP task shell:");
    println!("  - examples/bvp_task_shell_guide.rs");
    println!("    Minimal text-driven symbolic BVP example.");
    println!();
    println!("Related direct API guides:");
    println!("  - examples/symbolic/symbolic_construction_guide.rs");
    println!("    Basic symbolic expression construction, rename, substitute and pretty-print.");
    println!("  - examples/symbolic/symbolic_indexed_guide.rs");
    println!("    Indexed variables and small matrix/vector symbolic formulas.");
    println!("  - examples/symbolic/symbolic_lambdify_and_simplify_guide.rs");
    println!("    Simplify then evaluate with lambdify.");
    println!("  - examples/symbolic/symbolic_derivatives_guide.rs");
    println!("    Differentiate, simplify, and compare analytic vs numeric evaluation.");
    println!("  - examples/ode_api2_guide.rs");
    println!("    Direct IVP API without the text shell.");
    println!("  - examples/ivp_backends_guide.rs");
    println!("    Backend-oriented IVP comparison guide.");
    println!("  - examples/lsode2_numerical_guide.rs");
    println!("    LSODE2 pure numerical callbacks guide (analytical + FD Jacobian).");
    println!("  - examples/lsode2_lambdify_guide.rs");
    println!("    LSODE2 symbolic Lambdify guide.");
    println!("  - examples/lsode2_aot_guide.rs");
    println!("    LSODE2 symbolic AOT guide.");
    println!("  - examples/lsode2_manual_bdf_guide.rs");
    println!("    LSODE2 manual LSODE-style BDF-only selection.");
    println!("  - examples/lsode2_manual_adams_guide.rs");
    println!("    LSODE2 manual LSODE-style Adams-only selection.");
    println!("  - src/numerical/IVP_USER_GUIDE_EN.md");
    println!("    Full IVP guide (BDF/Radau/BE + RK45/DOPRI/AB4 + Universal API).");
    println!("  - src/numerical/IVP_USER_GUIDE_RU.md");
    println!("    Full IVP guide in Russian (same scope and examples).");
    println!("  - examples/bvp_backends_guide.rs");
    println!("    Backend-oriented BVP comparison guide.");
    println!("  - examples/banded_solvers_guide.rs");
    println!("    Guide to the native banded direct solvers.");
}
